# Generated by Django 6.0.7 on 2026-07-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_review_booking_review_edited_at_review_is_hidden_and_more'),
        ('movies', '0002_movie_banner_movie_certificate_movie_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='movies', to='admin_panel.genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='movies', to='admin_panel.language'),
        ),
        migrations.AddField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='movies/thumbnails/'),
        ),
    ]
