# Generated by Django 6.0.7 on 2026-07-31 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_backfill_booking_refs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('row_start', models.CharField(default='A', help_text='First row letter covered by this category', max_length=2)),
                ('row_end', models.CharField(default='Z', help_text='Last row letter covered by this category', max_length=2)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Snapshotted coupon discount share', max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Snapshotted GST amount for this seat', max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Snapshotted GST percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='booking',
            name='misc_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Snapshotted miscellaneous fee share', max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Snapshotted platform fee share', max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_category',
            field=models.CharField(blank=True, default='', help_text='Snapshotted seat category at booking time', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Snapshotted per-seat ticket price', max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Snapshotted amount charged for this seat', max_digits=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST percentage applied', max_digits=5),
        ),
        migrations.AddField(
            model_name='reservation',
            name='misc_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Miscellaneous fee (per booking)', max_digits=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Platform fee (per ticket)', max_digits=10),
        ),
        migrations.AddField(
            model_name='theater',
            name='screen_name',
            field=models.CharField(blank=True, default='Main', help_text='Screen shown for this show (e.g. Screen 1)', max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='convenience_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Platform fee + miscellaneous fee combined', max_digits=10),
        ),
        migrations.CreateModel(
            name='ShowPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='movies.seatcategory')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='movies.theater')),
            ],
            options={
                'ordering': ['category__display_order', 'category__name'],
                'unique_together': {('theater', 'category')},
            },
        ),
    ]
