# Generated by Django 6.0.7 on 2026-08-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_seatcategory_booking_discount_booking_gst_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', help_text='Booking lifecycle status', max_length=20),
        ),
    ]
