# Generated by Django 6.0.7 on 2026-08-03 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_alter_booking_options_alter_booking_booked_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booked_at', '-id']},
        ),
    ]
