# Generated by Django 6.0.7 on 2026-08-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_ticketdownload'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cinematographer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='music_director',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='production_company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='story',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='writer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
