# Generated by Django 6.0.7 on 2026-08-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_movie_cinematographer_movie_music_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='scan_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this ticket QR has been scanned'),
        ),
        migrations.AddField(
            model_name='booking',
            name='scanned_at',
            field=models.DateTimeField(blank=True, help_text='When the ticket QR was first scanned at the venue', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='scan_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this ticket QR has been scanned'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='scanned_at',
            field=models.DateTimeField(blank=True, help_text='When the ticket QR was first scanned at the venue', null=True),
        ),
    ]
