# Generated by Django 6.0.7 on 2026-08-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0022_booking_scan_count_booking_scanned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('movie', 'Movie'), ('laughing_therapy', 'Laughing Therapy'), ('live_concert', 'Live Concert')], db_index=True, default='movie', max_length=30),
        ),
    ]
