# Generated by Django 6.0.7 on 2026-08-16 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0025_emailoutbox_qr_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_ref', models.CharField(db_index=True, max_length=20)),
                ('movie', models.CharField(blank=True, default='', max_length=255)),
                ('theatre', models.CharField(blank=True, default='', max_length=255)),
                ('seats', models.CharField(blank=True, default='', help_text='Comma-separated seat numbers on the ticket', max_length=500)),
                ('result', models.CharField(choices=[('admitted', 'Admitted'), ('already_scanned', 'Already Scanned'), ('invalid', 'Invalid QR'), ('not_found', 'Not Found'), ('unpaid', 'Unpaid'), ('cancelled', 'Cancelled / Refunded')], db_index=True, default='admitted', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('scanned_by', models.ForeignKey(blank=True, help_text='Admin/staff user who operated the scanner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['booking_ref', 'scanned_at'], name='movies_tick_booking_611596_idx'), models.Index(fields=['result', 'scanned_at'], name='movies_tick_result_c8596e_idx')],
            },
        ),
    ]
