# Generated by Django 6.0.7 on 2026-08-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0026_ticketscan'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketscan',
            name='show_time',
            field=models.DateTimeField(blank=True, help_text='Scheduled show time for the scanned ticket', null=True),
        ),
    ]
