# Generated by Django 6.0.7 on 2026-08-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0027_ticketscan_show_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='When the booking was cancelled', null=True),
        ),
    ]
