# Generated by Django 6.0.7 on 2026-07-29 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_coupon_adminprofile_auditlog_notification_payment_and_more'),
        ('movies', '0002_movie_banner_movie_certificate_movie_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='movies.booking'),
        ),
        migrations.AddField(
            model_name='review',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Hidden from public view by admin'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_reported',
            field=models.BooleanField(default=False, help_text='Flagged as inappropriate by users'),
        ),
        migrations.AlterField(
            model_name='castmember',
            name='role',
            field=models.CharField(choices=[('hero', 'Hero'), ('heroine', 'Heroine'), ('villain', 'Villain'), ('supporting', 'Supporting'), ('guest', 'Guest Appearance'), ('other', 'Other')], default='actor', max_length=20),
        ),
    ]
