# Generated by Django 6.0.7 on 2026-07-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_review_booking_review_edited_at_review_is_hidden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castmember',
            name='role',
            field=models.CharField(choices=[('hero', 'Hero'), ('heroine', 'Heroine'), ('villain', 'Villain'), ('supporting', 'Supporting'), ('guest', 'Guest Appearance'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='show',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('sold_out', 'Sold Out'), ('paused', 'Paused')], default='active', max_length=20),
        ),
    ]
