# Generated by Django 6.0.7 on 2026-07-31 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_alter_castmember_role_alter_show_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Upper bound (inclusive). Leave empty for no upper limit.', max_digits=10, null=True)),
                ('rate', models.DecimalField(decimal_places=2, help_text='GST percentage for this slab', max_digits=5)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_fee_per_ticket', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('misc_fee_per_booking', models.DecimalField(decimal_places=2, default=2.5, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Configuration',
                'verbose_name_plural': 'Pricing Configurations',
            },
        ),
    ]
