# Generated by Django 6.0.7 on 2026-08-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_alter_payment_paid_at_alter_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('sold_out', 'Sold Out'), ('paused', 'Paused')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='show',
            name='time',
            field=models.TimeField(db_index=True),
        ),
    ]
