# Generated by Django 6.0.7 on 2026-08-05 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_screen_cols_per_section_screen_layout_spec_and_more'),
        ('movies', '0016_alter_seat_options_seat_category_seat_col_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='show',
            unique_together={('movie', 'theatre', 'screen', 'date', 'time')},
        ),
    ]
