# Generated by Django 6.0.7 on 2026-08-06 14:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_show_unique_slot'),
        ('movies', '0018_backfill_reservation_booking_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='admin_panel_user_id_ca998c_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['movie', 'is_approved', 'is_hidden'], name='admin_panel_movie_i_e8dde6_idx'),
        ),
    ]
