# Generated by Django 6.0.7 on 2026-07-31 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_gstslab_pricingconfig'),
        ('movies', '0009_seatcategory_booking_discount_booking_gst_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(default='razorpay', max_length=20)),
                ('gateway_order_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('gateway_payment_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('gateway_signature', models.CharField(blank=True, max_length=1024)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('status', models.CharField(choices=[('created', 'Created'), ('captured', 'Captured'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refund_requested', 'Refund Requested'), ('refunded', 'Refunded')], db_index=True, default='created', max_length=20)),
                ('method', models.CharField(blank=True, default='', help_text='Payment method reported by the gateway', max_length=50)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255)),
                ('coupon_code', models.CharField(blank=True, default='', max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Raw gateway response for auditing')),
                ('is_demo', models.BooleanField(default=False, help_text='True for demo/sandbox checkouts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('refund_id', models.CharField(blank=True, default='', max_length=255)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='movies.reservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='admin_panel_user_id_3a9bca_idx'), models.Index(fields=['reservation', 'status'], name='admin_panel_reserva_9e651d_idx')],
            },
        ),
    ]
