# Generated by Django 6.0.7 on 2026-08-01 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_paymenttransaction'),
        ('movies', '0012_theater_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='theater',
            field=models.OneToOneField(blank=True, help_text='Linked booking-flow show (movies.Theater) kept in sync with this Show', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_show', to='movies.theater'),
        ),
    ]
