# Generated by Django 6.0.7 on 2026-08-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_alter_show_date_alter_show_status_alter_show_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='cols_per_section',
            field=models.PositiveIntegerField(default=0, help_text='Max seats per section (left/right of the aisle) in a row'),
        ),
        migrations.AddField(
            model_name='screen',
            name='layout_spec',
            field=models.JSONField(blank=True, default=dict, help_text='Full seat-layout definition used to generate seats for shows on this screen'),
        ),
        migrations.AddField(
            model_name='screen',
            name='rows',
            field=models.PositiveIntegerField(default=0, help_text='Number of seat rows in the layout'),
        ),
        migrations.AddField(
            model_name='screen',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('imax', 'IMAX'), ('premium', 'Premium')], default='small', help_text='Screen class; drives the default seat layout', max_length=20),
        ),
    ]
