# Generated by Django 6.0.7 on 2026-08-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_reviewhelpful'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='confirmation_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='failure_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
