# Generated by Django 6.0.7 on 2026-08-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_paymenttransaction_confirmation_email_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='refund_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
