"""
Django settings for bookmyseat project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import sys
import dj_database_url

# Load .env file (gitignored) for local secrets like email SMTP credentials.
# python-dotenv is listed in requirements.txt, but guard the import so the app
# still boots from real environment variables on serverless platforms (Vercel)
# even if the package is missing from a cached/stale build.
try:
    from dotenv import load_dotenv
    # Explicitly load the .env that lives next to manage.py (BASE_DIR/.env)
    # so secrets resolve regardless of the directory the process is run from.
    load_dotenv(os.path.join(Path(__file__).resolve().parent.parent, '.env'))
except ImportError:
    pass
# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR is the backend/ folder (contains manage.py, .env, db.sqlite3, media/).
BASE_DIR = Path(__file__).resolve().parent.parent

# Project root contains the separated frontend/ folder.
PROJECT_ROOT = BASE_DIR.parent
# Separated frontend assets live outside the Django project folder.
FRONTEND_DIR = PROJECT_ROOT / 'frontend'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# True while running the test suite. Used to bypass short-lived feed caches so
# tests always see fresh data.
TESTING = 'test' in sys.argv

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-dev-only-7k9p2m4x8q1w6z3y5v0n7b2c4f6h8j0l'
    else:
        from django.core.exceptions import ImproperlyConfigured
        raise ImproperlyConfigured(
            'DJANGO_SECRET_KEY must be set when DEBUG is False.'
        )

ALLOWED_HOSTS = os.environ.get(
    'DJANGO_ALLOWED_HOSTS',
    '127.0.0.1,localhost,.vercel.app,.onrender.com,.railway.app',
).split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # movies MUST come before django.contrib.staticfiles: Django resolves
    # duplicate management commands by iterating INSTALLED_APPS in reverse, so
    # the earlier app wins. movies.runserver (which auto-starts the email
    # worker) has to beat staticfiles' runserver.
    'movies',
    'django.contrib.staticfiles',
    'users',
    'admin_panel',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'admin_panel.middleware.AdminIdentityMiddleware',
    'users.middleware.NoStoreMiddleware',
    'users.middleware.LoggedOutGuardMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTH_USER_MODEL='auth.User'

# Email delivery. Configure EMAIL_HOST etc. (or the .env / environment
# variables) to send real confirmation emails; otherwise emails are printed
# to the console for development.
#
# The console backend is ONLY a development convenience. In production it
# silently "sends" to stdout and marks outbox rows as delivered, which looks
# successful but delivers nothing — so when DEBUG is disabled we fail fast
# instead of ever falling back to it.
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', '')
if not EMAIL_BACKEND:
    if os.environ.get('EMAIL_HOST'):
        EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    else:
        EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
        if not DEBUG and not TESTING:
            from django.core.exceptions import ImproperlyConfigured
            raise ImproperlyConfigured(
                'EMAIL_HOST must be set when DEBUG is False. Production must '
                'never silently fall back to the console email backend, which '
                'accepts messages but sends nothing. Set EMAIL_HOST, '
                'EMAIL_HOST_PASSWORD, DEFAULT_FROM_EMAIL and SITE_URL (Render: '
                'Environment tab on the web service).'
            )
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587') or '587')
EMAIL_HOST_USER = os.environ.get(
    'EMAIL_HOST_USER', 'bookmyseat.official26@gmail.com'
)
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False') == 'True'
# Fail fast instead of hanging a request when the SMTP host is unreachable.
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '15') or '15')
DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL', 'BookMySeat <bookmyseat.official26@gmail.com>'
)

# Send via Brevo's HTTPS API (port 443) when set. Render's free tier blocks
# SMTP ports (25/465/587), so production uses BREVO_API_KEY instead of SMTP.
BREVO_API_KEY = os.environ.get('BREVO_API_KEY', '')

# Public site base URL used to build absolute links inside emails.
SITE_URL = os.environ.get('SITE_URL', '')

# Async email outbox (see movies/models.EmailOutbox): the process_email_outbox
# management command retries failed deliveries with exponential backoff using
# these knobs. Defaults target roughly a 1 hour delivery window.
EMAIL_OUTBOX_MAX_ATTEMPTS = int(os.environ.get('EMAIL_OUTBOX_MAX_ATTEMPTS', '6'))
EMAIL_OUTBOX_BACKOFF_BASE = int(os.environ.get('EMAIL_OUTBOX_BACKOFF_BASE_SECONDS', '60'))
EMAIL_OUTBOX_CLAIM_MAX_AGE = int(os.environ.get('EMAIL_OUTBOX_CLAIM_MAX_AGE_SECONDS', '600'))

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ---------------------------------------------------------------------------
# Media storage backend
#
# Render's web-service filesystem is EPHEMERAL: every restart, redeploy or
# spin-down rebuilds the container from git and wipes files uploaded at
# runtime. Storing admin-uploaded posters/banners on that disk is why images
# vanished after a while while PostgreSQL kept their paths.
#
# When CLOUDINARY_URL is configured (production), every ImageField/FileField
# switches to Cloudinary — uploads become permanent URLs and survive restarts,
# redeploys and the next day. No model changes are needed: FileField resolves
# its storage from STORAGES at runtime.
#
# Local development (no CLOUDINARY_URL) keeps the plain filesystem under
# backend/media/ exactly as before. Static files always stay local and are
# served by WhiteNoise in both modes — static and media remain separate.
if os.environ.get('CLOUDINARY_URL'):
    STORAGES = {
        'default': {
            'BACKEND': 'bookmyseat.cloudinary_storage.CloudinaryMediaStorage',
        },
        # Unchanged default so collectstatic/WhiteNoise behaviour is identical
        # whether or not cloud media storage is enabled.
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }


ROOT_URLCONF = 'bookmyseat.urls'
LOGIN_URL='/login/'

ADMIN_SESSION_TIMEOUT = 3600
SESSION_COOKIE_AGE = 28800
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
COOKIE_SECURE = os.environ.get(
    'COOKIE_SECURE', 'False' if DEBUG else 'True'
) == 'True'
SESSION_COOKIE_SECURE = os.environ.get(
    'SESSION_COOKIE_SECURE', str(COOKIE_SECURE).lower()
) == 'True'
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = os.environ.get(
    'CSRF_COOKIE_SECURE', str(COOKIE_SECURE).lower()
) == 'True'
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_NAME = 'bms_sessionid'

# Behind the HTTPS proxy of Render / Railway / Vercel the platform rewrites
# X-Forwarded-Proto to "https", which Django must trust so request.is_secure()
# and the secure cookie flags below behave correctly in production.
# Set DJANGO_TRUST_PROXY=False if the app is served directly (no proxy).
if not DEBUG and os.environ.get('DJANGO_TRUST_PROXY', 'True') == 'True':
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Security headers for production.
if not DEBUG:
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Cache. Uses Redis (via REDIS_URL) when available so rate limiting, OTP and
# analytics payload caching stay consistent across workers; otherwise falls
# back to a per-process LocMem cache for local development.
if os.environ.get('REDIS_URL'):
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': os.environ['REDIS_URL'],
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
            'KEY_PREFIX': 'bms',
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'bms-dev-cache',
        }
    }
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [str(FRONTEND_DIR / 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'admin_panel.context_processors.admin_notifications',
                'movies.context_processors.bms_cities',
                'users.context_processors.unread_notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'bookmyseat.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
#
# Local development (no DATABASE_URL): SQLite at backend/db.sqlite3.
# Production (DATABASE_URL present): PostgreSQL configured from the URL that
# Render / Railway / Supabase / Vercel provide. Connection pooling is enabled
# for long-lived processes (conn_max_age) and stale connections are revalidated
# on serverless platforms (conn_health_checks). SSL is required by default in
# production and can be toggled with DATABASE_SSL_REQUIRE.
if os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=600,
            conn_health_checks=True,
            ssl_require=(
                os.environ.get('DATABASE_SSL_REQUIRE', 'True' if not DEBUG else 'False')
                == 'True'
            ),
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Razorpay payment gateway
# https://razorpay.com/docs/payments/payment-gateway/
RAZORPAY_KEY_ID = os.environ.get('RAZORPAY_KEY_ID', '')
RAZORPAY_KEY_SECRET = os.environ.get('RAZORPAY_KEY_SECRET', '')
RAZORPAY_WEBHOOK_SECRET = os.environ.get('RAZORPAY_WEBHOOK_SECRET', '')

# When True the checkout page renders a demo/sandbox pay button that mimics a
# successful Razorpay callback so the whole flow can be exercised without keys.
RAZORPAY_DEMO_MODE = os.environ.get('RAZORPAY_DEMO_MODE', 'True') == 'True'

# Razorpay gateway diagnostics (order creation, checkout payload, signature
# verification, webhooks) are printed to the console during development.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'movies.gateway': {'handlers': ['console'], 'level': 'DEBUG', 'propagate': False},
        'movies.payments': {'handlers': ['console'], 'level': 'DEBUG', 'propagate': False},
        'movies.notifications': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True

# ---------------------------------------------------------------------------
# Showtime validation & late-entry window
# ---------------------------------------------------------------------------
# The theatre runs on Indian Standard Time; showtime status (upcoming /
# late-entry / expired) is always computed against this zone. Time display on
# the public site and in the admin panel is localised to it as well.
SHOWTIME_TIME_ZONE = os.environ.get('SHOWTIME_TIME_ZONE', TIME_ZONE)

# How many minutes after the scheduled start a show remains bookable with an
# explicit late-entry warning. After the window (or the movie's end time, if
# earlier) a show is EXPIRED and no longer bookable at all.
LATE_ENTRY_WINDOW_MINUTES = int(
    os.environ.get('LATE_ENTRY_WINDOW_MINUTES', '30')
)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [str(FRONTEND_DIR / 'static')]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise serves the app's static files in production (no separate web
# server / no deploy-time build step required on Vercel). USE_FINDERS serves
# straight from STATICFILES_DIRS, so `collectstatic` is not mandatory.
WHITENOISE_USE_FINDERS = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Test-only performance tweaks -------------------------------------------
# Real users keep the strong PBKDF2 hasher above. Under `manage.py test`, users
# live only in the throwaway test database, so hashing can be the (instant,
# insecure) MD5 hasher. This drops the full suite from minutes to seconds
# without any effect on production password storage.
if 'test' in sys.argv:
    PASSWORD_HASHERS = ['django.contrib.auth.hashers.MD5PasswordHasher']
