from django.urls import path
from . import views
urlpatterns=[
    path('', views.movie_list, name='movie_list'),
    path('<int:movie_id>/', views.movie_detail, name='movie_detail'),
    path('<int:movie_id>/review/', views.submit_review, name='submit_review'),
    path('review/<int:review_id>/report/', views.report_review, name='report_review'),
    path('review/<int:review_id>/helpful/', views.helpful_review, name='helpful_review'),
    path('<int:movie_id>/theaters/', views.theater_list, name='theater_list'),
    path('theater/<int:theater_id>/seats/book/', views.book_seats, name='book_seats'),
    path('theater/<int:theater_id>/seats/status/', views.seat_status, name='seat_status'),
    path('api/reserve/', views.reserve_seats_api, name='api_reserve'),
    path('api/reservation/<str:token>/modify/', views.modify_reservation_view, name='api_reservation_modify'),
    path('api/reservation/<str:token>/release/', views.release_reservation_view, name='api_reservation_release'),
    path('reservation/<str:token>/payment/', views.payment_page, name='payment_page'),
    path('api/payment/<str:token>/start/', views.payment_start_api, name='payment_start'),
    path('api/payment/<str:token>/verify/', views.payment_verify_api, name='payment_verify'),
    path('api/payment/<str:token>/failed/', views.payment_failed_api, name='payment_failed'),
    path('api/payment/webhook/', views.payment_webhook, name='payment_webhook'),
    path('reservation/<str:token>/confirmation/', views.booking_confirmation, name='booking_confirmation'),
    path('api/coupon/validate/', views.coupon_validate, name='api_coupon_validate'),
    path('api/ticket/<int:booking_id>/cancel/', views.cancel_booking_view, name='cancel_booking'),
    path('api/booking/<str:booking_ref>/cancel/', views.cancel_booking_ref_view, name='cancel_booking_ref'),
    path('ticket/<str:booking_ref>/', views.download_ticket, name='download_ticket'),
    path('ticket/<str:booking_ref>/pdf/', views.ticket_pdf, name='ticket_pdf'),
    path('api/ticket/verify/', views.verify_ticket_qr, name='verify_ticket_qr'),
    path('invoice/<str:booking_ref>/', views.booking_invoice, name='booking_invoice'),
    path('api/cleanup-expired/', views.cleanup_expired_reservations_view, name='api_cleanup_expired'),
    path('api/images/missing-log/', views.log_missing_image, name='log_missing_image'),
]