# Generated by Django 6.0.7 on 2026-07-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_genres_movie_languages_movie_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='movie',
            name='show_on_homepage',
            field=models.BooleanField(default=True, help_text='Show this movie on the homepage'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('coming_soon', 'Coming Soon'), ('now_showing', 'Now Showing'), ('archived', 'Archived'), ('hidden', 'Hidden')], default='draft', max_length=20),
        ),
    ]
