# Generated by Django 6.0.7 on 2026-07-30 13:45

import django.core.validators
from django.db import migrations, models
from django.db.models import Count


def remove_duplicate_seats(apps, schema_editor):
    Seat = apps.get_model('movies', 'Seat')
    duplicates = (
        Seat.objects.values('theater_id', 'seat_number')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
    )
    for dup in duplicates:
        seats = Seat.objects.filter(
            theater_id=dup['theater_id'],
            seat_number=dup['seat_number']
        )
        keep = seats.first()
        seats.exclude(id=keep.id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_is_deleted_movie_show_on_homepage_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_seats, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-release_date', 'name']},
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, upload_to='movies/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('theater', 'seat_number')},
        ),
    ]
