# Generated by Django 6.0.7 on 2026-08-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('sold_out', 'Sold Out'), ('paused', 'Paused')], default='active', help_text='Public booking visibility status, kept in sync with the admin Show', max_length=20),
        ),
    ]
