# Generated by Django 6.0.7 on 2026-08-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_alter_booking_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('coming_soon', 'Coming Soon'), ('now_showing', 'Now Showing'), ('archived', 'Archived'), ('hidden', 'Hidden')], db_index=True, default='draft', max_length=20),
        ),
    ]
