# Generated by Django 6.0.7 on 2026-08-05 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_alter_movie_name_alter_movie_release_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['row_idx', 'col_idx']},
        ),
        migrations.AddField(
            model_name='seat',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Pricing band this seat belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seats', to='movies.seatcategory'),
        ),
        migrations.AddField(
            model_name='seat',
            name='col_idx',
            field=models.PositiveIntegerField(default=0, help_text='Column index within the row starting at 0 (left to right)'),
        ),
        migrations.AddField(
            model_name='seat',
            name='couple_group',
            field=models.PositiveIntegerField(default=0, help_text='Couple-pair group id; seats sharing a non-zero group must be bought together'),
        ),
        migrations.AddField(
            model_name='seat',
            name='gap_before',
            field=models.BooleanField(default=False, help_text='Render an aisle gap before this seat within its row'),
        ),
        migrations.AddField(
            model_name='seat',
            name='is_best_view',
            field=models.BooleanField(default=False, help_text="Premium 'best view' seats for the screen"),
        ),
        migrations.AddField(
            model_name='seat',
            name='row_idx',
            field=models.PositiveIntegerField(default=0, help_text='Row index starting at 0 (0 is closest to the screen)'),
        ),
        migrations.AddField(
            model_name='seat',
            name='row_label',
            field=models.CharField(blank=True, default='', help_text='Display row label, e.g. A, B1, R-1', max_length=5),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('wheelchair', 'Wheelchair'), ('couple', 'Couple')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='seat',
            name='side',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center')], default='center', help_text='Screen side of the aisle gap', max_length=10),
        ),
        migrations.AddField(
            model_name='theater',
            name='layout_spec',
            field=models.JSONField(blank=True, default=dict, help_text="Snapshot of the screen seat-layout definition used to generate this show's seats"),
        ),
    ]
