# Generated by Django 6.0.7 on 2026-08-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_alter_seat_options_seat_category_seat_col_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='booking_ref',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Transaction-level booking ID shared by all seats (e.g. BMS39DBA878)', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='ticket_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of tickets booked in this reservation'),
        ),
    ]
