# Generated by Django 6.0.7 on 2026-08-06 14:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_alter_auditlog_created_at_and_more'),
        ('movies', '0018_backfill_reservation_booking_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='is_booked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='theater',
            name='time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status', 'expires_at'], name='movies_rese_status_0e3383_idx'),
        ),
    ]
