# Generated by Django 6.0.7 on 2026-08-08 13:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0023_movie_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(db_index=True, max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('plain_body', models.TextField(blank=True, default='')),
                ('html_body', models.TextField(blank=True, default='')),
                ('pdf_filename', models.CharField(blank=True, default='', max_length=255)),
                ('pdf_attachment', models.BinaryField(blank=True, help_text='Generated PDF M-ticket (application/pdf)', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Delivery attempts so far')),
                ('max_attempts', models.PositiveIntegerField(default=6, help_text='Attempts before the message is marked failed')),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, help_text='When the message becomes eligible for delivery; NULL once permanently failed', null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('locked_at', models.DateTimeField(blank=True, help_text='When a worker claimed this message', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='movies_emai_status_775647_idx')],
            },
        ),
    ]
